"""add_crypto_payments

Revision ID: 26d0bcad7795
Revises: 66a1d0ae6153
Create Date: 2026-04-30 03:04:10.401555

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26d0bcad7795'
down_revision: str | Sequence[str] | None = '66a1d0ae6153'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nowpayments_id', sa.String(), nullable=False),
    sa.Column('pay_address', sa.String(), nullable=True),
    sa.Column('pay_currency', sa.String(), nullable=False),
    sa.Column('pay_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_payments_nowpayments_id'), 'crypto_payments', ['nowpayments_id'], unique=True)
    op.create_index(op.f('ix_crypto_payments_user_id'), 'crypto_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_payments_user_id'), table_name='crypto_payments')
    op.drop_index(op.f('ix_crypto_payments_nowpayments_id'), table_name='crypto_payments')
    op.drop_table('crypto_payments')
    # ### end Alembic commands ###
