"""fix unit_price precision

Revision ID: 66a1d0ae6153
Revises: 1eb25ccf0262
Create Date: 2026-04-30 02:04:24.296236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a1d0ae6153'
down_revision: Union[str, Sequence[str], None] = '1eb25ccf0262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product_association', 'unit_price',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product_association', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
