"""empty message

Revision ID: 22f10f339b95
Revises: 9ec52c2c3325
Create Date: 2026-01-11 16:36:45.663962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f10f339b95'
down_revision: Union[str, Sequence[str], None] = '9ec52c2c3325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('event_slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_markets_event_id'), 'markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_markets_event_slug'), 'markets', ['event_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_event_slug'), table_name='markets')
    op.drop_index(op.f('ix_markets_event_id'), table_name='markets')

    op.drop_column('markets', 'event_slug')
    # ### end Alembic commands ###
