"""add uniq market_ids

Revision ID: 9ec52c2c3325
Revises: fca8ed2421ca
Create Date: 2026-01-08 11:46:47.145376

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ec52c2c3325'
down_revision: str | Sequence[str] | None = 'fca8ed2421ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_markets_embedding_hnsw'), table_name='markets', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # op.drop_index(op.f('ix_markets_embedding_ivfflat'), table_name='markets', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.drop_index(op.f('ix_markets_semantic_embedding_hnsw'), table_name='markets', postgresql_ops={'semantic_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # op.drop_index(op.f('ix_markets_semantic_embedding_ivfflat'), table_name='markets', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.drop_index(op.f('pairs_market_ids_gin'), table_name='pairs', postgresql_using='gin')
    op.create_unique_constraint(None, 'pairs', ['market_ids'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pairs', type_='unique')
    # op.create_index(op.f('pairs_market_ids_gin'), 'pairs', ['market_ids'], unique=False, postgresql_using='gin')
    # op.create_index(op.f('ix_markets_semantic_embedding_ivfflat'), 'markets', ['semantic_embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('ix_markets_semantic_embedding_hnsw'), 'markets', ['semantic_embedding'], unique=False, postgresql_ops={'semantic_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # op.create_index(op.f('ix_markets_embedding_ivfflat'), 'markets', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.create_index(op.f('ix_markets_embedding_hnsw'), 'markets', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
