"""add_series_ticker

Revision ID: fc901c6f5651
Revises: 22f10f339b95
Create Date: 2026-01-14 21:07:54.287819

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc901c6f5651'
down_revision: str | Sequence[str] | None = '22f10f339b95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('series_ticker', sa.String(), nullable=True))
    op.create_index(op.f('ix_markets_series_ticker'), 'markets', ['series_ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_series_ticker'), table_name='markets')
    op.drop_column('markets', 'series_ticker')
    # ### end Alembic commands ###
