"""empty message

Revision ID: fca8ed2421ca
Revises:
Create Date: 2025-12-24 22:57:39.289088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'fca8ed2421ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_market_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.Column('token_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('liquidity', sa.Numeric(), nullable=True),
    sa.Column('volume_24h', sa.Numeric(), nullable=True),
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('close_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('semantic_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('semantic_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_platform'), 'markets', ['platform'], unique=False)
    op.create_index(op.f('ix_markets_platform_market_id'), 'markets', ['platform_market_id'], unique=True)
    op.create_table('orderbooks',
    sa.Column('platform_market_id', sa.String(), nullable=False),
    sa.Column('orderbook', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderbooks_platform_market_id'), 'orderbooks', ['platform_market_id'], unique=True)
    op.create_table('pairs',
    sa.Column('market_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('title_channel_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_channel_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ---------- semantic_embedding ----------

    op.create_index(
        "ix_markets_semantic_embedding_ivfflat",
        "markets",
        ["semantic_embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
    )

    op.create_index(
        "ix_markets_semantic_embedding_hnsw",
        "markets",
        ["semantic_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={
            "semantic_embedding": "vector_cosine_ops",
        },
    )

    # ---------- embedding ----------

    op.create_index(
        "ix_markets_embedding_ivfflat",
        "markets",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
    )

    op.create_index(
        "ix_markets_embedding_hnsw",
        "markets",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={
            "embedding": "vector_cosine_ops",
        },
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairs')
    op.drop_index(op.f('ix_orderbooks_platform_market_id'), table_name='orderbooks')
    op.drop_table('orderbooks')
    op.drop_index(op.f('ix_markets_platform_market_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_platform'), table_name='markets')
    op.drop_table('markets')

    op.drop_index("ix_markets_embedding_hnsw", table_name="markets")
    op.drop_index("ix_markets_embedding_ivfflat", table_name="markets")

    op.drop_index("ix_markets_semantic_embedding_hnsw", table_name="markets")
    op.drop_index("ix_markets_semantic_embedding_ivfflat", table_name="markets")
    # ### end Alembic commands ###
